name: active_symbols
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  base_core:
    path: ../base_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
