name: tick_stream_deriv_one
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  tick_stream:
    path: ../../

  flutter_deriv_api:
    git:
      url: git@github.com:deriv-com/flutter-deriv-api.git
      ref: flutter-version-3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
