name: deriv_two
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  mini_mq:
    git:
      url: git@github.com:naif-deriv/DartMQ.git
      ref: master
      path: mini_mq

  # flutter_deriv_api:
  #   git:
  #     url: git@github.com:deriv-com/flutter-deriv-api.git
  #     ref: flutter-version-3

  deriv_adapters_plugins:
    # git:
    #   url:
    path: ../deriv_adapters_plugins

  deriv_application_layer:
    # git:
    #   url:
    path: ../deriv_application_layer

  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
