name: example_application
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  mini_mq:
    git:
      url: git@github.com:naif-deriv/DartMQ.git
      ref: master
      path: mini_mq

  flutter_deriv_api:
    git:
      url: git@github.com:deriv-com/flutter-deriv-api.git
      ref: flutter-version-3

  active_symbols_feature:
    git:
      url: git@github.com:naif-deriv/core-plugin-arch-poc.git
      ref: master
      path: plugins/deriv_one/active_symbols_feature

  ticks_stream_feature:
    git:
      url: git@github.com:naif-deriv/core-plugin-arch-poc.git
      ref: master
      path: plugins/deriv_one/ticks_stream_feature

  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
