name: deriv_application_layer
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  deriv_adapters_plugins:
    # git:
    #   url:
    path: ../deriv_adapters_plugins

  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  mini_mq:
    git:
      url: git@github.com:naif-deriv/DartMQ.git
      ref: master
      path: mini_mq

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
