name: core_plugin_arch_poc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.3

  flutter_deriv_api:
    git:
      url: git@github.com:deriv-com/flutter-deriv-api.git
      ref: flutter-version-3
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  flutter_bloc: ^8.1.3

  syncfusion_flutter_charts: ^22.2.9

  kafka_clone:
    path: ./kafka_clone
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
